"""Constants for the OpenAI Conversation integration."""
import homeassistant.helpers.config_validation as cv
import voluptuous as vol


DOMAIN = "dj_hass"
CONF_PROMPT = "prompt"
DEFAULT_PROMPT = """You are a radio-DJ to whom people can call and request songs by phone.
You can search and play music from backend by using the provided functions.
Your prompts may be generated by voice recognition, so some words and especially names may be misspelled.
Your responses may be played using text-to-speech, so avoid long responses and use spoken language.
Use humor in your responses and act as a DJ.
"""
CONF_CHAT_MODEL = "chat_model"
DEFAULT_CHAT_MODEL = "gpt-3.5-turbo"
CONF_MAX_TOKENS = "max_tokens"
DEFAULT_MAX_TOKENS = 500
CONF_TOP_P = "top_p"
DEFAULT_TOP_P = 1
CONF_TEMPERATURE = "temperature"
DEFAULT_TEMPERATURE = 0.5
CONF_SPOTIFY_CLIENT_ID = "spotify_client_id"
CONF_SPOTIFY_CLIENT_SECRET = "spotify_client_secret"

SPOTIFY_CONFIG_SCHEMA = vol.Schema(
    {
        DOMAIN: vol.Schema(
            {
                vol.Required(CONF_SPOTIFY_CLIENT_ID): cv.string,
                vol.Required(CONF_SPOTIFY_CLIENT_SECRET): cv.string
            }
        ),
    },
)